<?php

namespace App\Http\Middleware;

use App\Exceptions\BussinessException;
use App\ReturnCode;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Auth\Middleware\Authenticate as Middleware;
use Illuminate\Http\Request;

class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param Request $request
     * @return string|null
     */
    protected function redirectTo($request)
    {
        if (!$request->expectsJson()) {
            return route('login');
        }
    }

    /**
     * token认证失败处理
     * @param Request $request
     * @param array $guards
     * @throws BussinessException
     * @throws AuthenticationException
     */
    public function unauthenticated($request, array $guards)
    {
        if (!$request->expectsJson() || in_array('wx', $guards)) {
            // 保护器是wx时抛出规定异常
            throw new BussinessException(ReturnCode::UN_LOGIN);
        }
        parent::unauthenticated($request, $guards); // TODO: Change the autogenerated stub
    }
}
